jwt:
    secret: Z3V0c2lzc3Ryb25nZXJ0aGFuZ3JpZmZpdGhldmVuaWZncmlmZml0aHBvc3Nlc3Nlc2dvZGx5cG93ZXJzaGVzdGlsbGNhbm5vdGJlYXRndXRz
logging:
    level:
        org:
            hibernate:
                SQL: debug
                orm:
                    jdbc:
                        bind: 'trace'
        root: warn
spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/test_erp
        username: postgres
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    main:
        banner-mode: 'off'

singleServerConfig:
    address: "redis://127.0.0.1:${REDIS_PORT:6379}"
